name: sharink-backend

version: '3.4'
services:
  api:
    container_name: api
    restart: always
    build:
      context: .
      dockerfile: ./main/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - sharink-network
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - MONGO_HOST=${MONGO_HOST}
      - KAFKA_HOST=${KAFKA_HOST}
      - COMMON_RATE_LIMIT_MAX_REQUESTS=${COMMON_RATE_LIMIT_MAX_REQUESTS}
      - COMMON_RATE_LIMIT_WINDOW_MS=${COMMON_RATE_LIMIT_WINDOW_MS}
      - CORS_ORIGIN=${CORS_ORIGIN}
      - HOST=${HOST}
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - YA_ACCESS_TOKEN=${YA_ACCESS_TOKEN}
      - YA_UID=${YA_UID}

      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_USER=${REDIS_USER}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_TTL=${REDIS_TTL}

      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_LOGIN=${MONGO_LOGIN}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - MONGO_COLLECTION_NAME=${MONGO_COLLECTION_NAME}

      - KAFKA_HOST=${KAFKA_HOST}
      - KAFKA_PORT=${KAFKA_PORT}

  yandex:
    container_name: yandex
    restart: always
    build:
      context: .
      dockerfile: ./yandex-microservice/Dockerfile
    depends_on:
      - api
      - kafka
    networks:
      - sharink-network
    environment:
      - YA_ACCESS_TOKEN=${YA_ACCESS_TOKEN}
      - YA_UID=${YA_UID}

      - KAFKA_HOST=${KAFKA_HOST}
      - KAFKA_PORT=${KAFKA_PORT}

  youtube:
    container_name: youtube
    restart: always
    build:
      context: .
      dockerfile: ./youtube-microservice/Dockerfile
    depends_on:
      - api
      - kafka
    networks:
      - sharink-network
    environment:
      - KAFKA_HOST=${KAFKA_HOST}
      - KAFKA_PORT=${KAFKA_PORT}

  redis:
    container_name: ${REDIS_HOST}
    image: redis:5
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    restart: always
    volumes:
      - ./docker/redis/d–∞ta:/root/redis
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_USER=${REDIS_USER}
      - REDIS_DATABASES=16
    networks:
      - sharink-network
    env_file: ".env"

  mongodb:
    container_name: ${MONGO_HOST}
    image: mongo:3.6
    restart: always
    environment:
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /dev/null
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_LOGIN}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ./docker/mongo/data:/data/db
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    command: mongod --smallfiles --logpath=/dev/null # --quiet
    networks:
      - sharink-network
    env_file: ".env"

  zookeeper:
    image: zookeeper
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - 2181:2181
    networks:
      - sharink-network

  kafka:
    image: ches/kafka
    container_name: ${KAFKA_HOST}
    hostname: localhost
    ports:
      - 9092:9092
    environment:
      ZOOKEEPER_IP: zookeeper
    networks:
      - sharink-network

volumes:
  mongo-data:
networks:
  sharink-network:
